#Speed Check
function Checks/Movement/Speed/SpeedA
function Checks/Movement/Speed/SpeedB
function Checks/Movement/Speed/SpeedC
function Checks/Movement/Speed/SpeedD
function Checks/Movement/Speed/SpeedE
function Checks/Movement/Speed/SpeedF
function Checks/Movement/Speed/SpeedG
function Checks/Movement/Speed/SpeedH
function Checks/Movement/Speed/SpeedI
function Checks/Movement/Speed/SpeedJ
function Checks/Movement/Speed/SpeedK
#Fly Check
function Checks/Movement/Fly/FlyA
function Checks/Movement/Fly/FlyB
function Checks/Movement/Fly/FlyC
function Checks/Movement/Fly/FlyD
function Checks/Movement/Fly/FlyE
function Checks/Movement/Fly/FlyF
function Checks/Movement/Fly/FlyG
function Checks/Movement/Fly/FlyH
function Checks/Movement/Fly/FlyI
#NoSlow Check
function Checks/Movement/NoSlow/NoSlowA
function Checks/Movement/NoSlow/NoSlowB
function Checks/Movement/NoSlow/NoSlowC
function Checks/Movement/NoSlow/NoSlowD
function Checks/Movement/NoSlow/NoSlowE
function Checks/Movement/NoSlow/NoSlowF
#Jump Check
function Checks/Movement/Jump/JumpA
function Checks/Movement/Jump/JumpB
function Checks/Movement/Jump/JumpC
function Checks/Movement/Jump/JumpD
function Checks/Movement/Jump/JumpE
function Checks/Movement/Jump/JumpF
#Climb Check
function Checks/Movement/Climb/ClimbA
function Checks/Movement/Climb/ClimbB